/**
 * Pipeline for deploying main docker image to docker hub
 **/
pipeline{
    environment {
        registry = "muditchopra/terraform"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
	agent any

	stages {
		stage('Building Image') {
			steps{
                script {
                    dir("terraform"){
                        dockerImage = docker.build registry + ":latest"
                    }
                }//script
            }//steps
		}//stage
        stage('Test'){
            steps {
                script {
                    docker.image("muditchopra/terraform:latest").inside{
                        sh '/bin/sh /opt/test.sh'
                    }
                }
            }
        }
		stage('Deploy Image') {
			steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                    dockerImage.push()
                    }
                }//script
            }//stpes
		}//stage

	}//stages
     post { always { cleanWs() } }
}
