/**
 * Pipeline for deploying main docker image to docker hub
 **/
pipeline{
    environment {
        registry = "muditchopra/terraform"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
	agent any

	stages {
		stage('Building Image') {
			steps{
                script {
                    dockerImage = docker.build registry + ":latest"
                }//script
            }//steps
		}//stage

		stage('Deploy Image') {
			steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                    dockerImage.push()
                    }
                }//script
            }//stpes
		}//stage

	}

}
